### PR TITLE
[vpj][server] Make Zstd compression threadsafe

### LINKED ISSUE #88: [BUG] Zstd compression is not thread safe and causes JVM crash
### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### Venice version

0.4.6

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 20.0)**: Linux and Mac
- **JDK version**: JDK 11

### Describe the problem

If a hybrid store enables zstd compression, the Leader will compress the data from RT and write to VT. If there are multiple leaders for a version on a storage node, the JVM crashes since compression in ZstdWithDictCompressor is not thread safe.

[hs_err_pid31413.log](https://github.com/linkedin/venice/files/9913695/hs_err_pid31413.log)

### Tracking information

_No response_

### Code to reproduce bug

```java
@Test
public void testParallelZstdCompression() {
  byte[] dictionary = ZstdWithDictCompressor.buildDictionaryOnSyntheticAvroData();
  VeniceCompressor compressor = new CompressorFactory().createCompressorWithDictionary(dictionary, Zstd.maxCompressionLevel());

  int threadPoolSize = 100;
  int numThreads = threadPoolSize * 10;
  ExecutorService executorService = Executors.newFixedThreadPool(threadPoolSize);
  List<Thread> threads = new ArrayList<>(numThreads);
  for (int i = 0; i < numThreads; i++) {
    Thread t = new Thread(() -> {
      Random rd = new Random();
      byte[] data = new byte[50];
      rd.nextBytes(data);
      try {
        compressor.compress(data);
      } catch (IOException e) {
        throw new RuntimeException(e);
      }
    });
    threads.add(t);
    executorService.submit(t);
  }

  TestUtils.waitForNonDeterministicAssertion(10, TimeUnit.SECONDS, false, true, () -> {
    for (Thread t : threads) {
      Assert.assertEquals(t.getState(), Thread.State.TERMINATED);
    }
  });
}
```

### What component(s) does this bug affect?

- [ ] `Controller`: This is the control-plane for Venice. Used to create/update/query stores and their metadata.
- [ ] `Router`: This is the stateless query-routing layer for serving read requests.
- [X] `Server`: This is the component that persists all the store data.
- [ ] `VenicePushJob`: This is the component that pushes derived data from Hadoop to Venice backend.
- [ ] `Thin Client`: This is a stateless client users use to query Venice Router for reading store data.
- [ ] `Fast Client`: This is a stateful client users use to query Venice Server for reading store data.
- [ ] `Da Vinci Client`: This is an embedded, stateful client that materializes store data locally.
- [ ] `Alpini`: This is the framework that fast-client and routers use to route requests to the storage nodes that have the data.
- [ ] `Samza`: This is the library users use to make nearline updates to store data.
- [ ] `Admin Tool`: This is the stand-alone client used for ad-hoc operations on Venice.
- [ ] `Scripts`: These are the various ops scripts in the repo.

### PR DESCRIPTION
**Pull request by nisargthakkar**
## Make Zstd compression threadsafe

This commit uses a thread-local `ZstdCompressorCtx` objects since they are not thread-safe. To help with closing of these objects cleanly, a new `CloseableThreadLocal` class is also created

Resolves #88

## How was this PR tested?

Added new unit tests.
Internal CI - JDK11 #6647

## Does this PR introduce any user-facing changes?

- [X] No. You can skip the rest of this section.
- [ ] Yes. Make sure to explain your proposed changes and call out the behavior change.

### CODE REVIEW

File: internal/venice-client-common/src/main/java/com/linkedin/venice/compression/ZstdWithDictCompressor.java [hunk 1]
```diff
@@ -21,30 +22,23 @@
...
   public ByteBuffer compress(ByteBuffer data) {
-    if (data.isDirect()) {
-      // TODO: It might be a decent refactor to add a pool of direct memory buffers so as to always leverage the this
-      // interface and copy the results of the compression back into the passed in ByteBuffer. That would avoid
-      // some of the data copy going on here.
-      return compressor.compress(data);
-    } else {
-      return ByteBuffer.wrap(compressor.compress(ByteUtils.extractByteArray(data)));
-    }
+    return Zstd.compress(data, compressorDictionary);
```
Comment (ZacAttack) [inline internal/venice-client-common/src/main/java/com/linkedin/venice/compression/ZstdWithDictCompressor.java:41]: This is interesting.  Does it work on direct memory here?

**Review by ZacAttack — COMMENTED** [review]
I think this looks good, thanks for the quick fix!

I'd like to know more if this works now for direct memory.  Might be a good down the road option to improve performance (though of course not necessary for this review).  If it's available, I'd like to resurrect the deleted TODO

**Review by FelixGV — APPROVED** [review]
Thank you!

File: internal/venice-client-common/src/main/java/com/linkedin/venice/compression/ZstdWithDictCompressor.java (hunk 1 above)
Comment (nisargthakkar) [reply internal/venice-client-common/src/main/java/com/linkedin/venice/compression/ZstdWithDictCompressor.java:41]: I was surprised too - but in the reverse direction. If I traverse the call stack, I reach this function that says `srcBuf` must be direct
```java
    /**
     * Compresses the data in buffer 'srcBuf'
     *
     * @param srcBuf the source buffer - must be direct. It is assumed that the `position()` of the
     *               buffer marks the beginning of the uncompressed data to be compressed, and that
     *               the `limit()` of this buffer marks its end.
     *               <p>
     *               When this method returns successfully, its `position()` will be set to its initial `limit()`.
     *               </p>
     * @return A newly allocated direct ByteBuffer containing the compressed data.
     */
    public ByteBuffer compress(ByteBuffer srcBuf) throws ZstdException {
```
But in the test case, we use non-direct buffer (`ByteBuffer.wrap`)

I modified a test case to test direct BB, non-direct BB and byte[] cases and this is getting enforced in the Zstd lib. Will fix and update it

File: internal/venice-client-common/src/main/java/com/linkedin/venice/compression/ZstdWithDictCompressor.java [hunk 2]
```diff
@@ -21,18 +23,18 @@
...
-    this.dictionary = dictionary;
-    compressor = new ZstdCompressCtx().loadDict(this.dictionary).setLevel(level);
+    this.compressorDictionary = new ZstdDictCompress(dictionary, level);
+    this.decompressorDictionary = new ZstdDictDecompress(dictionary);
   }
 
   @Override
   public byte[] compress(byte[] data) {
-    return compressor.compress(data);
+    return Zstd.compress(data, compressorDictionary);
```
Comment (gaojieliu) [inline internal/venice-client-common/src/main/java/com/linkedin/venice/compression/ZstdWithDictCompressor.java:37]:
```
public static byte[] compress(byte[] src, ZstdDictCompress dict) throws ZstdException {
        ZstdCompressCtx ctx = new ZstdCompressCtx();
        try {
            ctx.loadDict(dict);
            ctx.setLevel(dict.level());
            return ctx.compress(src);
        } finally {
            ctx.close();
        }
    }
```
This method will construct a new instance of `ZstdCompressCtx` and load the dict every time, and I am wondering whether this could be too heavy or not.
Is it possible to run some benchmark before committing this code?
If it is too expensive, can we use thread-local variables to prevent race condition?

Comment (gaojieliu) [reply internal/venice-client-common/src/main/java/com/linkedin/venice/compression/ZstdWithDictCompressor.java:37]: Here is the javadoc of :`ZstdCompressCtx`
```
Create a context for faster compress operations One such context is required for each thread - put this in a ThreadLocal.
```

It seems using `ThreadLocal` is the right way to achieve best performance without race condition, so can you double check?

**Review by gaojieliu — CHANGES_REQUESTED** [review]

File: internal/venice-client-common/src/main/java/com/linkedin/venice/compression/ZstdWithDictCompressor.java (hunk 2 above)
Comment (nisargthakkar) [reply internal/venice-client-common/src/main/java/com/linkedin/venice/compression/ZstdWithDictCompressor.java:37]: That's a great idea

File: internal/venice-client-common/src/main/java/com/linkedin/venice/compression/ZstdWithDictCompressor.java [hunk 3]
```diff
@@ -64,13 +62,12 @@ public ByteBuffer decompress(byte[] data, int offset, int length) throws IOExcep
 
   @Override
   public InputStream decompress(InputStream inputStream) throws IOException {
-    return new ZstdInputStream(inputStream).setDict(this.decompressorDictionary);
+    return new ZstdInputStream(inputStream).setDict(this.dictionary);
```
Comment (FelixGV) [inline internal/venice-client-common/src/main/java/com/linkedin/venice/compression/ZstdWithDictCompressor.java:65]: The latest version of this lib supports optionally passing a `BufferPool` in this constructor. Would be interesting to experiment with this (not in this PR though).

https://javadoc.io/doc/com.github.luben/zstd-jni/latest/com/github/luben/zstd/ZstdInputStream.html

**Review by FelixGV — APPROVED** [review]
Thanks Nisarg!

File: internal/venice-client-common/src/main/java/com/linkedin/venice/compression/ZstdWithDictCompressor.java [hunk 4]
```diff
@@ -67,7 +67,7 @@ public InputStream decompress(InputStream inputStream) throws IOException {
 
   @Override
   public void close() throws IOException {
-    compressor.close();
+    compressor.get().close();
```
Comment (FelixGV) [inline internal/venice-client-common/src/main/java/com/linkedin/venice/compression/ZstdWithDictCompressor.java:70]: Actually, there is a problem here... this will result in closing only the compressor associated with the thread calling close, but none of the others... this is a leak. Using `ThreadLocal` introduces some trickiness. We may need this class to hold a collection of compressors, which get added to by the `ThreadLocal` initializing closure... and then in this function iterate over all of them and close them all. May be good to revise our other usages of TL to figure out if we have other leaks elsewhere as well...

**Review by FelixGV — CHANGES_REQUESTED** [review]

File: internal/venice-client-common/src/main/java/com/linkedin/venice/compression/ZstdWithDictCompressor.java (hunk 4 above)
Comment (nisargthakkar) [reply internal/venice-client-common/src/main/java/com/linkedin/venice/compression/ZstdWithDictCompressor.java:70]: Yes, I realized this last night and am adding a `CloseableThreadLocal` class

File: internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java [hunk 5]
```diff
@@ -0,0 +1,95 @@
...
+   * Removes the current thread's value for this thread-local
+   * variable. It also triggers {@code close} on the current
+   * thread's value. If this thread-local variable is subsequently
+   * {@linkplain #get read} by the current thread, its value will be
+   * reinitialized by invoking its {@code initialValue} method,
+   * unless its value is {@linkplain #set set} by the current thread
+   * in the interim. This may result in multiple invocations of the
+   * {@code initialValue} method in the current thread.
+   */
+  public void remove() {
```
Comment (FelixGV) [inline internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java:56]: May be simpler to not implement this and the other methods we don't use...

File: internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java [hunk 6]
```diff
@@ -0,0 +1,95 @@
...
+   * Returns the value in the current thread's copy of this
+   * thread-local variable.  If the variable has no value for the
+   * current thread, it is first initialized to the value returned
+   * by an invocation of the {@code initialValue} method.
+   *
+   * @return the current thread's value of this thread-local
+   */
+  public T get() {
+    T item = threadLocal.get();
+    itemSet.add(item);
```
Comment (FelixGV) [inline internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java:42]: Can we do this inside the supplier closure serving as initializer to the actual ThreadLocal? I would prefer not doing a set addition on the hot path if it ain't necessary.

**Review by FelixGV — CHANGES_REQUESTED** [review]
Minor comments. Thanks!

File: internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java [hunk 7]
```diff
@@ -0,0 +1,95 @@
...
+/**
+ * A wrapper of {@link ThreadLocal} for {@link AutoCloseable} objects.
+ * Java's {@link ThreadLocal} only dereferences the thread-local objects
+ * when the {@link Thread} exits which triggers their garbage collection.
+ * It does not {@code close} the {@link AutoCloseable} thread-local objects.
+ * @param <T> The {@link AutoCloseable} type whose objects will be held by an object of this class.
+ */
+public class CloseableThreadLocal<T extends AutoCloseable> implements AutoCloseable {
+  private static final Logger LOGGER = LogManager.getLogger(CloseableThreadLocal.class);
+  private final Set<T> itemSet = VeniceConcurrentHashMap.newKeySet();
```
Comment (gaojieliu) [inline internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java:18]: Why not just use `ConcurrentSkipListSet` instead?

File: internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java (hunk 6 above)
Comment (nisargthakkar) [reply internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java:42]: Sure. That makes sense

File: internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java (hunk 7 above)
Comment (nisargthakkar) [reply internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java:18]: I wasn't aware of this. However, we used `ConcurrentSet` from Netty previously - which was deprecated and the recommendation there is to use [ConcurrentHashMap.newKeySet](https://netty.io/4.1/api/io/netty/util/internal/ConcurrentSet.html). We have adopted this in our codebase in `Utils#newConcurrentSet`. I couldn't use the same util class in this PR since it is present in `venice-common` whereas this class is in `venice-client-common`.

Moving Utils class to `venice-client-common` would involve lots of changes and I want to avoid them in this PR

Let me know what you think?

File: internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java (hunk 5 above)
Comment (nisargthakkar) [reply internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java:56]: I wanted this class to keep high-level API parity with `ThreadLocal` since this is a Util class

Comment (FelixGV) [reply internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java:56]: Sure, that's fine. In that case, `remove` should close the previous value, if there is any...

Comment (nisargthakkar) [reply internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java:56]: Aha. Yep. I missed that

File: internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java (hunk 7 above)
Comment (gaojieliu) [reply internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java:18]: So `VeniceConcurrentHashMap` doesn't provide an overrided implementation of `newKeySet`, so `newKeySet` will return a set based on `ConcurrentHashMap` and if we want to leverage the optimization implemented in `VeniceConcurrentHashMap`, we need to re-impl `newKeySet` to use `VeniceConcurrentHashMap` instead of the default `ConcurrentHashMap`:
```
public static <K> KeySetView<K,Boolean> newKeySet() {
        return new KeySetView<K,Boolean>
            (new ConcurrentHashMap<K,Boolean>(), Boolean.TRUE);
    }
``` 

`VeniceConcurrentHashMap` is in `venice-client-common`, and I guess we could use it directly.

Comment (nisargthakkar) [reply internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java:18]: Currently, I am already using `VeniceConcurrentHashMap`.

The [bug](https://bugs.openjdk.org/browse/JDK-8161372) that `VeniceConcurrentHashMap` solves is only in `computeIfAbsent` function. Do we need to override the `newKeySet` function for that? This would also trigger some class movement since VeniceConcurrentHashMap would need move to `java.util.concurrent` package to access the Package-private constructor for KeySetView
```java
        KeySetView(ConcurrentHashMap<K,V> map, V value) {  // non-public
            super(map);
            this.value = value;
        }
```

Comment (FelixGV) [reply internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java:18]: That is not possible. Only JDK classes are allowed in that package.

Comment (nisargthakkar) [reply internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java:18]: [This](http://hg.openjdk.java.net/jdk9/jdk9/jdk/rev/fe0d3813e6c3) was the commit that fixed [JDK-8161372](https://bugs.openjdk.org/browse/JDK-8161372). There was a change in `putVal` which is also used in `KeySetView#add`. So, I guess it would have been best to use `ConcurrentSkipListSet` like Gaojie initially suggested. 

However, I need to change the datastructure to a map now to address [this review comment](https://github.com/linkedin/venice/pull/89#discussion_r1012364353). I'll try `ConcurrentSkipListSet` if I decide to remove the unused functions instead

Comment (gaojieliu) [reply internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java:18]: SG

File: internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java [hunk 8]
```diff
@@ -0,0 +1,95 @@
...
+  /**
+   * Sets the current thread's copy of this thread-local variable
+   * to the specified value. Most subclasses will have no need to
+   * override this method, relying solely on the {@code initialValue}
+   * method to set the values of thread-locals.
+   *
+   * @param value the value to be stored in the current thread's copy of
+   *        this thread-local.
+   */
+  public void set(T value) {
```
Comment (gaojieliu) [inline internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java:70]: The semantics of this function conflicts with the `remove` function since `remove` function will close the `threadLocal.get()`, which can be created by `ClosableThreadLocal` or passed by `set` function.
So I think we need to define the ownership of the value, and if it is constructed by this class, this class should close it, and it is passed by `set`, I don't think `remove` or `set` or `close` should close the internal instance.

Maybe it is simpler to just remove the support of `set` function completely to simplify the ownership management of this internal variable.

**Review by gaojieliu — CHANGES_REQUESTED** [review]

File: internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java (hunk 8 above)
Comment (nisargthakkar) [reply internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java:70]: Yes, that makes sense. Will remove `set` for now. No need to unnecessarily complicate things.

File: internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java [hunk 9]
```diff
@@ -41,67 +43,31 @@ public T get() {
...
-        LOGGER.error(e);
-      }
+  private void closeQuietly(T value) {
+    try {
+      value.close();
+    } catch (Exception e) {
+      LOGGER.error(e);
     }
+
+    valueSet.remove(value);
```
[the remark this answers is not in the document]
Comment (nisargthakkar) [reply internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java]: Makes sense. Updated

File: internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java [hunk 10]
```diff
@@ -0,0 +1,72 @@
...
+
+/**
+ * A wrapper of {@link ThreadLocal} for {@link AutoCloseable} objects.
+ * Java's {@link ThreadLocal} only dereferences the thread-local objects
+ * when the {@link Thread} exits which triggers their garbage collection.
+ * It does not {@code close} the {@link AutoCloseable} thread-local objects.
+ * @param <T> The {@link AutoCloseable} type whose objects will be held by an object of this class.
+ */
+public class CloseableThreadLocal<T extends AutoCloseable> implements AutoCloseable {
+  private static final Logger LOGGER = LogManager.getLogger(CloseableThreadLocal.class);
```
Comment (gaojieliu) [inline internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java:19]: Shall we throw `UnsupportedOperationException` for `set` method? Otherwise, the replaced internal variable won't be `closed` properly?

Comment (nisargthakkar) [reply internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java:19]: This class doesn't extend `ThreadLocal` at the moment. It just creates an internal `ThreadLocal` delegate. Should it extend `ThreadLocal`?

Comment (gaojieliu) [reply internal/venice-client-common/src/main/java/com/linkedin/venice/utils/concurrent/CloseableThreadLocal.java:19]: My bad, that should be fine then.
We don't need to extend `ThreadLocal` here.

**Review by gaojieliu — APPROVED** [review]

**Review by FelixGV — APPROVED** [review]
