### PR TITLE
[dvc] Flag enablement for automatic subscription of partitions

### LINKED ISSUE #650: [BUG] Reconcile on disk state with assigned partitions for given resource and delete unused partitions
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### Venice version

Observed since March in production

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 20.0)**: Marner 5.15.111.1-1.cm2
- **JDK version**: 17

### Describe the problem

Currently the on-disk state inside the rocksDB folder of a venice server for a give resource (store version) can contain folders for partitions that are no longer assigned to the host, due to missed "partition drops".

We need to ensure that only the known (metadata ?)  or "assigned" partitions are present in the folder for each store_version , and remove the rest very quickly in order to recover disk space.

It is NOT sufficient to clean up this data on start without some introspection.  Venice relies on delayed rebalance on it's controller to avoid unnecessary bootstraps, so some examination may be needed to determine what the appropriate disk state should be. 

### Tracking information

_No response_

### Code to reproduce bug

_No response_

### What component(s) does this bug affect?

- [ ] `Controller`: This is the control-plane for Venice. Used to create/update/query stores and their metadata.
- [ ] `Router`: This is the stateless query-routing layer for serving read requests.
- [X] `Server`: This is the component that persists all the store data.
- [ ] `VenicePushJob`: This is the component that pushes derived data from Hadoop to Venice backend.
- [ ] `VenicePulsarSink`: This is a Sink connector for Apache Pulsar that pushes data from Pulsar into Venice.
- [ ] `Thin Client`: This is a stateless client users use to query Venice Router for reading store data.
- [ ] `Fast Client`: This is a stateful client users use to query Venice Server for reading store data.
- [x] `Da Vinci Client`: This is an embedded, stateful client that materializes store data locally.
- [ ] `Alpini`: This is the framework that fast-client and routers use to route requests to the storage nodes that have the data.
- [ ] `Samza`: This is the library users use to make nearline updates to store data.
- [ ] `Admin Tool`: This is the stand-alone client used for ad-hoc operations on Venice.
- [ ] `Scripts`: These are the various ops scripts in the repo.

### PR DESCRIPTION
**Pull request by kristyelee**
## [dvc] Flag enablement for automatic subscription of partitions

In this PR, to make sure the correct partitions are subscribed/added to the subscription set in processes of Da Vinci Client, a code change is introduced to include a flag (`DA_VINCI_SUBSCRIBE_ON_DISK_PARTITIONS_AUTOMATICALLY`) for enabling/confirming automatic subscription of on-disk partitions. This flag is added to the config map in the VeniceConfigLoader. Flag value is checked during bootstrapping in DaVinciBackend in case automatic subscription is not wanted, so that subscription occurs correctly.
Applying this issue to Da Vinci Client which has information over partitions in storage. 

DA_VINCI_SUBSCRIBE_ON_DISK_PARTITIONS_AUTOMATICALLY is by default set to true, where in DaVinciBackend the subscription by default occurs. 

This PR is an extension of the PR https://github.com/linkedin/venice/pull/1196 that checks which partitions should be kept [in `StorageService`] and applies the check in `VeniceServer`.

Resolves #650 

## How was this PR tested?

A corresponding test will be written. 
EDIT: A corresponding integration test has been written. Example testing includes the case where the config key is set to false to prevent automatic subscription. 

## Does this PR introduce any user-facing changes?

- [X] No. You can skip the rest of this section.
- [ ] Yes. Make sure to explain your proposed changes and call out the behavior change.

### CODE REVIEW

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/StoreBackend.java [hunk 1]
```diff
@@ -154,7 +154,13 @@ synchronized CompletableFuture<Void> subscribe(
       // Recreate store config that was potentially deleted by unsubscribe.
       config.store();
     }
+
+    ComplementSet<Integer> unassignedPartitionSet = ComplementSet.newSet(subscription);
```
Comment (kristyelee) [inline clients/da-vinci-client/src/main/java/com/linkedin/davinci/StoreBackend.java:158]: Upon bootstrapping, it seems that there is a setting to throw a VeniceException when a version is present. 
Bootstrapping is invoked in DaVinciBackend. 
Additionally, subscription of partitions is invoked in Da Vinci Client where set of partitions can be passed into the subscribe function directly.

Comment (kvargha) [reply clients/da-vinci-client/src/main/java/com/linkedin/davinci/StoreBackend.java:158]: What can happen is that when you call `unsubscribe` [subscription](https://github.com/linkedin/venice/blob/ce23e3895159478b5305714644f9bbeb85c1251e/clients/da-vinci-client/src/main/java/com/linkedin/davinci/StoreBackend.java#L198-L211) can be empty, causing it to delete the current version.

Also, I don't think `subscribe` is the right place to perform the validation. If a user is subscribing in a for loop, not everything would have been added to subscription yet on the first n-1 invocations. It would be better to do this validation somewhere we can guarantee all subscriptions have been performed. `DaVinciBackend::bootstrap` might be a good place.

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java [hunk 2]
```diff
@@ -474,6 +475,8 @@ private synchronized void bootstrap() {
       AbstractStorageEngine storageEngine = storageService.getStorageEngine(versionTopic);
       aggVersionedStorageEngineStats.setStorageEngine(versionTopic, storageEngine);
       StoreBackend storeBackend = getStoreOrThrow(storeName);
+      ComplementSet<Integer> persistedPartitionIds = ComplementSet.newSet(storageEngine.getPersistedPartitionIds());
+      storeBackend.unsubscribe(persistedPartitionIds);
```
Comment (kvargha) [inline clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java:479]: This would unsubscribe every partition on disk, which isn't what we want to happen.

We want to unsubscribe persisted partitions that don't exist in `storeBackend::subscription`

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java [hunk 3]
```diff
@@ -466,16 +468,22 @@ private synchronized void bootstrap() {
...
+        List<Integer> partitions = storeNameToPartitionListMap.get(storeName);
+        String versionTopic = version.kafkaTopicName();
+        LOGGER.info("Bootstrapping partitions {} for {}", partitions, versionTopic);
+        AbstractStorageEngine storageEngine = storageService.getStorageEngine(versionTopic);
+        aggVersionedStorageEngineStats.setStorageEngine(versionTopic, storageEngine);
+        StoreBackend storeBackend = getStoreOrThrow(storeName);
+        ComplementSet<Integer> subscription = ComplementSet.newSet(storeBackend.getSubscription());
+        ComplementSet<Integer> unassignedPartitionSet = ComplementSet.newSet(storageEngine.getPersistedPartitionIds());
+        unassignedPartitionSet.removeAll(subscription);
+        storeBackend.unsubscribe(unassignedPartitionSet);
```
Comment (kvargha) [inline clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java:483]: With Jialin's new approach, we won't need to unsubscribe here.

We'll just keep the state on disk, but not automatically subscribe.

Although we pay the cost of extra disk space, at least we save in CPU/Memory.

File: internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java [hunk 4]
```diff
@@ -97,6 +97,9 @@ private ConfigKeys() {
   public static final String DA_VINCI_CURRENT_VERSION_BOOTSTRAPPING_QUOTA_BYTES_PER_SECOND =
       "da.vinci.current.version.bootstrapping.quota.bytes.per.second";
 
+  // Prevent automatic subscription of partitions while bootstrapping.
+  public static final String DA_VINCI_BOOTSTRAP_SUBSCRIPTION_DISABLED = "da.vinci.bootstrap.subscription.disabled";
```
Comment (kvargha) [inline internal/venice-common/src/main/java/com/linkedin/venice/ConfigKeys.java:101]: Can we rename this to `da.vinci.subscribe.on.disk.partitions.automatically`?

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java (hunk 3 above)
Comment (kristyelee) [reply clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java:483]: [This resolves the [comment](https://github.com/linkedin/venice/pull/1332#discussion_r1870376282) above over subscription.]

Comment (kristyelee) [reply clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java:483]: Right now, a ConfigKey is used to enable automatic subscription of on disk partitions.

File: internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java [hunk 5]
```diff
@@ -1283,6 +1283,94 @@ public void testBootstrap(DaVinciConfig daVinciConfig) throws Exception {
     }
   }
 
+  @Test(timeOut = TEST_TIMEOUT, dataProvider = "dv-client-config-provider", dataProviderClass = DataProviderUtils.class)
+  public void testBootstrapSubscription(DaVinciConfig clientConfig) throws Exception {
```
Comment (kvargha) [inline internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java:1287]: Since `DA_VINCI_SUBSCRIBE_ON_DISK_PARTITIONS_AUTOMATICALLY` is already true by default, we should instead write a test where it's set to false.

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/AvroGenericDaVinciClient.java [hunk 6]
```diff
@@ -710,6 +711,7 @@ private VeniceConfigLoader buildVeniceConfig() {
         .put(CLUSTER_NAME, clusterName)
         .put(ZOOKEEPER_ADDRESS, zkAddress)
         .put(KAFKA_BOOTSTRAP_SERVERS, kafkaBootstrapServers)
+        .put(DA_VINCI_SUBSCRIBE_ON_DISK_PARTITIONS_AUTOMATICALLY, true)
```
Comment (ZacAttack) [inline clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/AvroGenericDaVinciClient.java:714]: Maybe this should default to false since it's a change in behavior?  @sixpluszero what do you think?

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java [hunk 7]
```diff
@@ -466,16 +468,18 @@ private synchronized void bootstrap() {
...
-    storeNameToBootstrapVersionMap.forEach((storeName, version) -> {
-      List<Integer> partitions = storeNameToPartitionListMap.get(storeName);
-      String versionTopic = version.kafkaTopicName();
-      LOGGER.info("Bootstrapping partitions {} for {}", partitions, versionTopic);
-      AbstractStorageEngine storageEngine = storageService.getStorageEngine(versionTopic);
-      aggVersionedStorageEngineStats.setStorageEngine(versionTopic, storageEngine);
-      StoreBackend storeBackend = getStoreOrThrow(storeName);
-      storeBackend.subscribe(ComplementSet.newSet(partitions), Optional.of(version));
-    });
+    if (configLoader.getCombinedProperties().getBoolean(DA_VINCI_SUBSCRIBE_ON_DISK_PARTITIONS_AUTOMATICALLY, true)) {
```
Comment (ZacAttack) [inline clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java:471]: This looks like a good start, but do we need to do clean up?  @sixpluszero @kvargha ?

Comment (ZacAttack) [reply clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java:471]: Maybe we add a method to the interface which allows users to clean up unsubscribed state?

File: internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java [hunk 8]
```diff
@@ -83,15 +86,7 @@
...
-import com.linkedin.venice.utils.DataProviderUtils;
-import com.linkedin.venice.utils.ForkedJavaProcess;
-import com.linkedin.venice.utils.IntegrationTestPushUtils;
-import com.linkedin.venice.utils.Pair;
-import com.linkedin.venice.utils.PropertyBuilder;
-import com.linkedin.venice.utils.TestUtils;
-import com.linkedin.venice.utils.TestWriteUtils;
-import com.linkedin.venice.utils.Utils;
-import com.linkedin.venice.utils.VeniceProperties;
+import com.linkedin.venice.utils.*;
```
Comment (ZacAttack) [inline internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java:89]: nit turn off * imports

File: internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java [hunk 9]
```diff
@@ -1283,6 +1278,88 @@ public void testBootstrap(DaVinciConfig daVinciConfig) throws Exception {
...
+        metricsRepository,
+        backendConfig)) {
+      DaVinciClient<Integer, Object> client1 = factory.getAndStartGenericAvroClient(storeName1, daVinciConfig);
+
+      // Test non-existent key access
+      client1.subscribeAll().get();
+      assertNull(client1.get(KEY_COUNT + 1).get());
+
+      // Test single-get access
+      Map<Integer, Integer> keyValueMap = new HashMap<>();
```
Comment (ZacAttack) [inline internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java:1310]: Let's repeat this logic on the reinstantiation but make sure it always returns null/empty since we don't want to serve data we're not subscribed to.

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java (hunk 7 above)
Comment (kvargha) [reply clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java:471]: Gaojie proposed that we keep the state on disk to play it on the safe side, as with a new version it will automatically get cleaned up.

File: internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java [hunk 10]
```diff
@@ -1283,6 +1287,97 @@ public void testBootstrap(DaVinciConfig daVinciConfig) throws Exception {
...
+
+        Integer expectedValue = cluster.createVersion(storeName1, KEY_COUNT);
+        TestUtils.waitForNonDeterministicAssertion(TEST_TIMEOUT, TimeUnit.MILLISECONDS, () -> {
+          for (int k = 0; k < KEY_COUNT; ++k) {
+            Object readValue = client1.get(k).get();
+            assertEquals(readValue, expectedValue);
+          }
+        });
+      }
+    }
```
Comment (kvargha) [inline internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java:1351]: I don't think we need this for this test.

File: internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java [hunk 11]
```diff
@@ -1283,6 +1287,97 @@ public void testBootstrap(DaVinciConfig daVinciConfig) throws Exception {
...
+      }
+
+      client1.subscribe(partitions);
+      client1.unsubscribeAll();
+
+      DaVinciBackend daVinciBackend = AvroGenericDaVinciClient.getBackend();
+      if (daVinciBackend != null) {
+        StoreBackend storeBackend = daVinciBackend.getStoreOrThrow(storeName1);
+        ComplementSet<Integer> subscription = storeBackend.getSubscription();
+        assertTrue(subscription.isEmpty());
```
Comment (kvargha) [inline internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/endToEnd/DaVinciClientTest.java:1376]: What we can do here instead is we can stick with the default partition count of 3 instead of modifying it, and in the new client we only subscribe to 2 partitions and validate that `subscription` only has 2 in the `ComplementSet`.

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/AvroGenericDaVinciClient.java (hunk 6 above)
Comment (sixpluszero) [reply clients/da-vinci-client/src/main/java/com/linkedin/davinci/client/AvroGenericDaVinciClient.java:714]: Just to clarify, this is the current behavior, we should mark it as true.

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java [hunk 12]
```diff
@@ -665,6 +669,10 @@ protected void handleStoreChanged(StoreBackend storeBackend) {
     storeBackend.trySubscribeDaVinciFutureVersion();
   }
 
+  protected void executeBootstrapping() {
+    bootstrap();
+  }
+
```
Comment (kvargha) [inline clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java:675]: Instead of doing this, can you change the access modifier on `bootstrap()` to `protected`?

File: clients/da-vinci-client/src/test/java/com/linkedin/davinci/DaVinciBackendTest.java [hunk 13]
```diff
@@ -139,4 +167,101 @@ public void testBootstrappingAwareCompletableFuture()
...
+
+    // DA_VINCI_SUBSCRIBE_ON_DISK_PARTITIONS_AUTOMATICALLY == false
+    when(mockCombinedProperties.getBoolean(anyString(), anyBoolean())).thenReturn(false);
+    doCallRealMethod().when(backend).executeBootstrapping();
+    backend.executeBootstrapping();
+
+    ComplementSet<Integer> subscription = mockStoreBackend.getSubscription();
+    assertTrue(subscription.contains(0));
+    assertTrue(subscription.contains(1));
+    assertFalse(subscription.contains(2));
```
Comment (kvargha) [inline clients/da-vinci-client/src/test/java/com/linkedin/davinci/DaVinciBackendTest.java:265]: Can you add another section to this test where `DA_VINCI_SUBSCRIBE_ON_DISK_PARTITIONS_AUTOMATICALLY` == `true` and all of the partitions are in `subscription`?

Comment (kristyelee) [reply clients/da-vinci-client/src/test/java/com/linkedin/davinci/DaVinciBackendTest.java]: This has been added.

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java (hunk 12 above)
Comment (kristyelee) [reply clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java]: Reverted access modifier of `bootstrap()` back to `private`. Used reflection of method in unit testing for correct outcome.

Comment (sixpluszero) [reply clients/da-vinci-client/src/main/java/com/linkedin/davinci/DaVinciBackend.java]: Hmm, I have a different opinion on this. Using reflection is generally not recommend in unit test. It is considered less readable and maintainable for other developer and it breaks encapsulation of private modifier. 
We can use default modifier (just nothing) or protected to make it accessible in unit test.

File: clients/da-vinci-client/src/test/java/com/linkedin/davinci/DaVinciBackendTest.java [hunk 14]
```diff
@@ -139,4 +168,114 @@ public void testBootstrappingAwareCompletableFuture()
...
+    ingestionListenerField.setAccessible(true);
+    ingestionListenerField.set(backend, ingestionListener);
+    KafkaStoreIngestionService storeIngestionService = mock(KafkaStoreIngestionService.class);
+    Field storeIngestionServiceField = DefaultIngestionBackend.class.getDeclaredField("storeIngestionService");
+    storeIngestionServiceField.setAccessible(true);
+    storeIngestionServiceField.set(ingestionBackend, storeIngestionService);
+    Field ingestionServiceField = DaVinciBackend.class.getDeclaredField("ingestionService");
+    ingestionServiceField.setAccessible(true);
+    ingestionServiceField.set(backend, storeIngestionService);
+    doNothing().when(ingestionBackend).addIngestionNotifier(any());
```
Comment (kvargha) [inline clients/da-vinci-client/src/test/java/com/linkedin/davinci/DaVinciBackendTest.java:258]: Since `ingestionBackend` gets defined inside `bootstrap`, can we try removing some of the unnecessary mocks?

File: clients/da-vinci-client/src/test/java/com/linkedin/davinci/DaVinciBackendTest.java [hunk 15]
```diff
@@ -139,4 +163,103 @@ public void testBootstrappingAwareCompletableFuture()
...
 
+  @Test
+  public void testBootstrappingSubscription()
+      throws IllegalAccessException, NoSuchFieldException, NoSuchMethodException, InvocationTargetException {
+    DaVinciBackend backend = mock(DaVinciBackend.class);
+    StorageService mockStorageService = mock(StorageService.class);
+
+    Field storageServiceField = DaVinciBackend.class.getDeclaredField("storageService");
+    storageServiceField.setAccessible(true);
+    storageServiceField.set(backend, mockStorageService);
```
Comment (kvargha) [inline clients/da-vinci-client/src/test/java/com/linkedin/davinci/DaVinciBackendTest.java:174]: We don't need this as storageService is now being mocked by line 187.

**Review by sixpluszero — APPROVED** [review]
LGTM, thank you!
