### PR TITLE
[server] Dropping unassigned partitions

### LINKED ISSUE #650: [BUG] Reconcile on disk state with assigned partitions for given resource and delete unused partitions
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### Venice version

Observed since March in production

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 20.0)**: Marner 5.15.111.1-1.cm2
- **JDK version**: 17

### Describe the problem

Currently the on-disk state inside the rocksDB folder of a venice server for a give resource (store version) can contain folders for partitions that are no longer assigned to the host, due to missed "partition drops".

We need to ensure that only the known (metadata ?)  or "assigned" partitions are present in the folder for each store_version , and remove the rest very quickly in order to recover disk space.

It is NOT sufficient to clean up this data on start without some introspection.  Venice relies on delayed rebalance on it's controller to avoid unnecessary bootstraps, so some examination may be needed to determine what the appropriate disk state should be. 

### Tracking information

_No response_

### Code to reproduce bug

_No response_

### What component(s) does this bug affect?

- [ ] `Controller`: This is the control-plane for Venice. Used to create/update/query stores and their metadata.
- [ ] `Router`: This is the stateless query-routing layer for serving read requests.
- [X] `Server`: This is the component that persists all the store data.
- [ ] `VenicePushJob`: This is the component that pushes derived data from Hadoop to Venice backend.
- [ ] `VenicePulsarSink`: This is a Sink connector for Apache Pulsar that pushes data from Pulsar into Venice.
- [ ] `Thin Client`: This is a stateless client users use to query Venice Router for reading store data.
- [ ] `Fast Client`: This is a stateful client users use to query Venice Server for reading store data.
- [x] `Da Vinci Client`: This is an embedded, stateful client that materializes store data locally.
- [ ] `Alpini`: This is the framework that fast-client and routers use to route requests to the storage nodes that have the data.
- [ ] `Samza`: This is the library users use to make nearline updates to store data.
- [ ] `Admin Tool`: This is the stand-alone client used for ad-hoc operations on Venice.
- [ ] `Scripts`: These are the various ops scripts in the repo.

### PR DESCRIPTION
**Pull request by kristyelee**
## Summary, imperative, start upper case, don't end with a period
The goal is to remove unassigned partitions that are on disk state

This involves storage service and engine, which upon starting (constructed), will go through folders on disk and verify status of folders
Helix's ideal state is used for consulting partitions and their assignment
The change proposed includes defining a function in VeniceServer that goes through partitions in idealState and compares to partitions in storageEngine
StorageEngine object initialization is also being updated to run the new function that performs this verification. 

Resolves #650 

## How was this PR tested?
Will write corresponding test.
EDIT: A unit test has been written.

## Does this PR introduce any user-facing changes?
- [X] No. You can skip the rest of this section.
- [ ] Yes. Make sure to explain your proposed changes and call out the behavior change.

### CODE REVIEW

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java [hunk 1]
```diff
@@ -587,6 +587,19 @@ void resubscribeForAllPartitions() throws InterruptedException {
...
+   * Removes partitions that are not subscribed / not assigned.
+   */
+
+  public synchronized void removeUnsubscribedPartitions() {
+    throwIfNotRunning();
+    for (PartitionConsumptionState partitionConsumptionState: partitionConsumptionStateMap.values()) {
+      if (!partitionConsumptionState.isSubscribed()) {
+        partitionConsumptionStateMap.remove(partitionConsumptionState.getPartition(), partitionConsumptionState);
+      }
+    }
```
Comment (kvargha) [inline clients/da-vinci-client/src/main/java/com/linkedin/davinci/kafka/consumer/StoreIngestionTask.java:600]: I believe in the meeting we discussed that this isn't the correct way to check for partitions to be removed. Please correct me if I'm wrong.

File: services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java [hunk 2]
```diff
@@ -42,10 +44,7 @@
 import com.linkedin.venice.listener.ServerReadMetadataRepository;
 import com.linkedin.venice.listener.ServerStoreAclHandler;
 import com.linkedin.venice.listener.StoreValueSchemasCacheService;
-import com.linkedin.venice.meta.ReadOnlyLiveClusterConfigRepository;
-import com.linkedin.venice.meta.ReadOnlySchemaRepository;
-import com.linkedin.venice.meta.ReadOnlyStoreRepository;
-import com.linkedin.venice.meta.StaticClusterInfoProvider;
+import com.linkedin.venice.meta.*;
```
Comment (kvargha) [inline services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java:47]: Please don't import everything. IntelliJ does this automatically, which is a bit annoying.

File: services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java [hunk 3]
```diff
@@ -64,13 +63,13 @@
 import com.linkedin.venice.utils.Utils;
 import com.linkedin.venice.utils.lazy.Lazy;
 import io.tehuti.metrics.MetricsRepository;
-import java.util.ArrayList;
-import java.util.Collections;
-import java.util.List;
-import java.util.Optional;
+import java.util.*;
```
Comment (kvargha) [inline services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java:66]: Same here

**Review by kvargha — CHANGES_REQUESTED** [review]

File: internal/venice-common/src/main/java/com/linkedin/venice/helix/SafeHelixDataAccessor.java [hunk 4]
```diff
@@ -82,7 +82,7 @@ public <T extends HelixProperty> boolean updateProperty(PropertyKey key, DataUpd
     return helixDataAccessor.updateProperty(key, updater, value);
   }
 
-  public <T extends HelixProperty> T getProperty(PropertyKey key) {
+  public static <T extends HelixProperty> T getProperty(PropertyKey key) {
```
Comment (kvargha) [inline internal/venice-common/src/main/java/com/linkedin/venice/helix/SafeHelixDataAccessor.java:85]: It looks like making this static is causing your tests to fail.

**Review by kvargha — CHANGES_REQUESTED** [review]

File: services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java [hunk 5]
```diff
@@ -714,7 +714,13 @@ private Function<String, Boolean> functionToCheckWhetherStorageEngineShouldBeKep
     return storageEngineName -> {
       String storeName = Version.parseStoreFromKafkaTopicName(storageEngineName);
 
-      AbstractStorageEngine storageEngine = storageService.getStorageEngine(storageEngineName);
```
[the remark this answers is not in the document]
Comment (kvargha) [reply services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java]: `checkWhetherStorageEngineShouldBeKeptOrNot` determines whether or not the entire `storageEngine` should be dropped, and where it's called it assumes that the `storageEngine` hasn't been opened yet.

What we should do here is modify the `StorageService` constructor to take another function that determines whether a partition should be kept or not. Ex: `checkWhetherStoragePartitionShouldBeKeptOrNot`

This new function can be invoked [here](https://github.com/linkedin/venice/blob/04aeaebb1fa56b5f392336074120ac9eb72acff1/clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java#L256C13-L256C55) after the `storageEngine` has been opened.

[the remark this answers is not in the document]
Comment (kristyelee) [reply services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java]: This idea makes sense. I will integrate this.

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java [hunk 6]
```diff
@@ -88,6 +89,7 @@ public class StorageService extends AbstractVeniceService {
       boolean restoreDataPartitions,
       boolean restoreMetadataPartitions,
       Function<String, Boolean> checkWhetherStorageEngineShouldBeKeptOrNot,
+      Function<AbstractStorageEngine, Void> checkWhetherStoragePartitionsShouldBeKeptOrNot,
```
Comment (kvargha) [inline clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java:92]: Can we create an additional constructor that doesn't have `checkWhetherStoragePartitionsShouldBeKeptOrNot`, so if users don't want to use this, they wouldn't have to pass in a functional interface that does nothing.

Comment (kristyelee) [reply clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java:92]: Ok, that sounds correct; `checkWhetherStoragePartitionsShouldBeKeptOrNot` is mainly being written in VeniceServer.

File: services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (kristyelee) [reply services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java]: Operations involving Helix [`HelixParticipationService`, `SafeHelixDataAccessor`] may require that services are started for `StorageService.` [requires that Venice server has started]. `SafeHelixDataAccessor` is used to obtain the ideal state as referenced in #650. Will have to check the structure here so that `checkWhetherStoragePartitionsShouldBeKeptOrNot` executes correctly.

[the remark this answers is not in the document]
Comment (kvargha) [reply services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java]: Try moving the execution of `checkWhetherStoragePartitionsShouldBeKeptOrNot` to after `HelixParticipationService` is initialized in VeniceServer.

File: services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java [hunk 7]
```diff
@@ -601,6 +600,10 @@ public void start() throws VeniceException {
       service.start();
     }
 
+    for (AbstractStorageEngine storageEngine: storageService.getStorageEngineRepository().getAllLocalStorageEngines()) {
```
Comment (kristyelee) [inline services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java:603]: I have moved the function here which is after services start, so that `HelixParticipationService` is started/initialized for referencing the ideal state in function.
I have reorganized the code in `StorageService` to its initial state.

Comment (kvargha) [reply services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java:603]: It looks like `HelixParticipationService` is started asynchronously, and it is causing some tests to fail.

We can try using [managerFuture](https://github.com/linkedin/venice/blob/df1c0b9f3b19a7dc4fbd3113512e3a21abbc278f/services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java#L356C3-L356C83). This will runs things after `HelixParticipationService` has started.

Ex:
```
managerFuture.thenApply(manager -> {
      // Call checkWhetherStoragePartitionsShouldBeKeptOrNot here
});
```

**Comment by kristyelee** [comment]
A few tests still have yet to pass with the changes that include the check for partition assignment. [e.g. this [test](https://github.com/linkedin/venice/actions/runs/11132688423/job/30943346267?pr=1196)] 
I have to check whether these are related to the changes I've submitted; also some of these tests seem to pass locally.

File: services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (kristyelee) [reply services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java]: (Resolution is here: https://github.com/linkedin/venice/pull/1196#discussion_r1781747306; when `HelixParticipationService` is started, `managerFuture` is completed in `HelixParticipationService.`).

**Comment by kristyelee** [comment]
(Suggested addition to code, that seems directly useful but is no longer / not used actively:

In the `HelixParticipationService` file, similar to the getInstance function, I also wrote a getHelixManager function. I tried using this before in access after `HelixParticipationService` is instantiated, but have changed this implementation. )

**Comment by kristyelee** [comment]
> (Suggested addition to code, that seems directly useful but is no longer / not used actively:
> 
> In the `HelixParticipationService` file, similar to the getInstance function, I also wrote a getHelixManager function. I tried using this before in access after `HelixParticipationService` is instantiated, but have changed this implementation. )

(Reverted code in this file back to original state but thought I should make a note of this).

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java [hunk 8]
```diff
@@ -371,6 +375,38 @@ public synchronized AbstractStorageEngine openStore(
     return engine;
   }
 
+  public synchronized void checkWhetherStoragePartitionsShouldBeKeptOrNot(SafeHelixManager manager) {
+    if (getStorageEngineRepository() == null || manager == null) {
```
Comment (ZacAttack) [inline clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java:379]: nit: getStorageEngineRepository() == null isn't needed.  The getter is based off of a final member variable.

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java [hunk 9]
```diff
@@ -371,6 +375,38 @@ public synchronized AbstractStorageEngine openStore(
...
+    for (AbstractStorageEngine storageEngine: getStorageEngineRepository().getAllLocalStorageEngines()) {
+      String storageEngineName = storageEngine.getStoreVersionName();
+      String storeName = Version.parseStoreFromKafkaTopicName(storageEngineName);
+      PropertyKey.Builder propertyKeyBuilder =
+          new PropertyKey.Builder(configLoader.getVeniceClusterConfig().getClusterName());
+      SafeHelixDataAccessor helixDataAccessor = manager.getHelixDataAccessor();
+      IdealState idealState = helixDataAccessor.getProperty(propertyKeyBuilder.idealStates(storeName));
+
+      if (idealState == null) {
+        return;
```
Comment (ZacAttack) [inline clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java:391]: This seems wrong.  This will abort the whole function, but we would want to iterate on the remainder of the storage engines to determine if we should keep them.  I think instead of return, we should use continue

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java [hunk 10]
```diff
@@ -371,6 +375,38 @@ public synchronized AbstractStorageEngine openStore(
...
+
+      Set<Integer> idealStatePartitionIds = new HashSet<>();
+
+      idealState.getPartitionSet().stream().forEach(partitionId -> {
+        idealStatePartitionIds.add(Integer.parseInt(partitionId));
+      });
+      Set<Integer> storageEnginePartitionIds = storageEngine.getPartitionIds();
+
+      for (Integer storageEnginePartitionId: storageEnginePartitionIds) {
+        if (idealStatePartitionIds.contains(storageEnginePartitionId)) {
```
Comment (ZacAttack) [inline clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java:402]: This also isn't quite right.  The ideal state is the superset of all partitions for the store.  All partitions ID's in the storageEngine will be in the superset.

We need to parse more information from the ideal state.  Specifically, for each partition that is on this node, we need to determine if the ideal state for that partition id contains the node name.

To better paint the picture, an ideal state is a big json document that looks like this:

>    "Test_Store_Migration_Demo_v1_0": {
>       "lor1-app56585.prod.linkedin.com_1690": "LEADER",
>       "lor1-app56614.prod.linkedin.com_1690": "STANDBY",
>       "lor1-app110448.prod.linkedin.com_1690": "STANDBY"
>     },
>     "Test_Store_Migration_Demo_v1_1": {
>       "lor1-app56586.prod.linkedin.com_1690": "LEADER",
>       "lor1-app71895.prod.linkedin.com_1690": "STANDBY",
>       "lor1-app111181.prod.linkedin.com_1690": "STANDBY"
>     },

Here, for partitions 1 and 0, we have three hosts assigned roles for that partition.  What we should do is, does the current host we're working with reside in these lists?

File: services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java [hunk 11]
```diff
@@ -310,14 +312,20 @@ private List<AbstractVeniceService> createServices() {
         ? new RocksDBMemoryStats(metricsRepository, "RocksDBMemoryStats", plainTableEnabled)
         : null;
 
+    boolean whetherToRestoreDataPartitions = !isIsolatedIngestion()
```
Comment (ZacAttack) [inline services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java:315]: @sixpluszero , can you confirm this to be right?

I think this is PR we maybe shouldn't bother with this.  The original code has this hard coded to true, i think we should just pass true instead of potentially altering the behavior as this juncture.

File: services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java [hunk 12]
```diff
@@ -310,14 +312,20 @@ private List<AbstractVeniceService> createServices() {
...
         veniceConfigLoader,
         storageEngineStats,
         rocksDBMemoryStats,
         storeVersionStateSerializer,
         partitionStateSerializer,
-        metadataRepo);
+        metadataRepo,
+        whetherToRestoreDataPartitions,
+        true,
+        functionToCheckWhetherStorageEngineShouldBeKeptOrNot());
```
Comment (ZacAttack) [inline services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java:328]: in the way that you've structured this PR it seems what you're doing is waiting for the managerFuture to complete as your means to do the local state clean up.  That's not a bad idea actually, I think that's actually pretty clever.  However, if you do that, then we don't need to mess with this at all.  Instead we can leave this code alone, and just use the shortened constructor that we were using before.

**Review by ZacAttack — CHANGES_REQUESTED** [review]

File: services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java (hunk 12 above)
Comment (kristyelee) [reply services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java]: (Revised).

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java [hunk 13]
```diff
@@ -371,6 +375,38 @@ public synchronized AbstractStorageEngine openStore(
...
+      SafeHelixDataAccessor helixDataAccessor = manager.getHelixDataAccessor();
+      IdealState idealState = helixDataAccessor.getProperty(propertyKeyBuilder.idealStates(storeName));
+
+      if (idealState == null) {
+        return;
+      }
+
+      Set<Integer> idealStatePartitionIds = new HashSet<>();
+
+      idealState.getPartitionSet().stream().forEach(partitionId -> {
```
[the remark this answers is not in the document]
Comment (kristyelee) [reply clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java]: I have updated this code and reflected this understanding.

**Comment by kristyelee** [comment]
I wrote the related unit test for this PR. 
GitHub tests pass for program, except for one Integration test unrelated to my change.

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java [hunk 14]
```diff
@@ -371,6 +376,43 @@ public synchronized AbstractStorageEngine openStore(
...
+          int partitionId = RocksDBUtils.parsePartitionIdFromPartitionDbName(partitionDbName);
+          if (!storageEnginePartitionIds.contains(partitionId)) {
+            continue;
+          }
+          for (String hostName: entry.getValue().keySet()) {
+            if (hostName.equals(instanceHostName)) {
+              keepPartition = true;
+              break;
+            }
+          }
```
Comment (kvargha) [inline clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java:407]: Instead of looping over every key, can we instead check if the key `instanceHostName` exists in `entry`?

File: clients/da-vinci-client/src/test/java/com/linkedin/davinci/storage/StorageServiceTest.java [hunk 15]
```diff
@@ -121,4 +136,76 @@ public void testGetStoreAndUserPartitionsMapping() {
...
+    ZNRecord record = new ZNRecord("testId");
+    Map<String, Map<String, String>> mapFields = new HashMap<>();
+    Map<String, String> testPartitionZero = new HashMap<>();
+    Map<String, String> testPartitionOne = new HashMap<>();
+    testPartitionZero.put("lor1-app56585.prod.linkedin.com_1690", "LEADER");
+    testPartitionZero.put("lor1-app56614.prod.linkedin.com_1690", "STANDBY");
+    testPartitionZero.put("lor1-app110448.prod.linkedin.com_1690", "STANDBY");
+    testPartitionOne.put("lor1-app56586.prod.linkedin.com_1690", "LEADER");
+    testPartitionOne.put("lor1-app71895.prod.linkedin.com_1690", "STANDBY");
+    testPartitionOne.put("lor1-app111181.prod.linkedin.com_1690", "STANDBY");
```
Comment (kvargha) [inline clients/da-vinci-client/src/test/java/com/linkedin/davinci/storage/StorageServiceTest.java:180]: Instead of using actual LinkedIn host names, can you create general ones?

File: clients/da-vinci-client/src/test/java/com/linkedin/davinci/storage/StorageServiceTest.java [hunk 16]
```diff
@@ -121,4 +136,76 @@ public void testGetStoreAndUserPartitionsMapping() {
...
+    mapFields.put("test_store_v1_0", testPartitionZero);
+    mapFields.put("test_store_v1_1", testPartitionOne);
+    record.setMapFields(mapFields);
+    when(idealState.getRecord()).thenReturn(record);
+    when(manager.getInstanceName()).thenReturn("lor1-app56586.prod.linkedin.com_1690");
```
Comment (kvargha) [inline clients/da-vinci-client/src/test/java/com/linkedin/davinci/storage/StorageServiceTest.java:185]: Same here

File: clients/da-vinci-client/src/test/java/com/linkedin/davinci/storage/StorageServiceTest.java [hunk 17]
```diff
@@ -121,4 +136,76 @@ public void testGetStoreAndUserPartitionsMapping() {
...
+    storageEngineRepositoryField.set(mockStorageService, mockStorageEngineRepository);
+    when(mockStorageService.getStorageEngineRepository()).thenReturn(mockStorageEngineRepository);
+    when(mockStorageService.getStorageEngineRepository().getAllLocalStorageEngines()).thenReturn(localStorageEngines);
+    Field configLoaderField = StorageService.class.getDeclaredField("configLoader");
+    configLoaderField.setAccessible(true);
+    configLoaderField.set(mockStorageService, mockVeniceConfigLoader);
+
+    doCallRealMethod().when(mockStorageService).checkWhetherStoragePartitionsShouldBeKeptOrNot(manager);
+    mockStorageService.checkWhetherStoragePartitionsShouldBeKeptOrNot(manager);
+    Assert.assertFalse(abstractStorageEngine.containsPartition(0));
```
Comment (kvargha) [inline clients/da-vinci-client/src/test/java/com/linkedin/davinci/storage/StorageServiceTest.java:209]: Can you add this check:
`verify(abstractStorageEngine.dropPartition(0))`

File: clients/da-vinci-client/src/test/java/com/linkedin/davinci/storage/StorageServiceTest.java (hunk 15 above)
Comment (kristyelee) [reply clients/da-vinci-client/src/test/java/com/linkedin/davinci/storage/StorageServiceTest.java]: Updated

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java [hunk 18]
```diff
@@ -371,6 +376,42 @@ public synchronized AbstractStorageEngine openStore(
...
+
+      if (idealState != null) {
+        Set<Integer> idealStatePartitionIds = new HashSet<>();
+        Set<String> partitionSet = idealState.getPartitionSet();
+        partitionSet.stream().forEach(partitionDbName -> {
+          idealStatePartitionIds.add(RocksDBUtils.parsePartitionIdFromPartitionDbName(partitionDbName));
+        });
+
+        Map<String, Map<String, String>> mapFields = idealState.getRecord().getMapFields();
+        for (Map.Entry<String, Map<String, String>> entry: mapFields.entrySet()) {
```
Comment (kvargha) [inline clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java:401]: Instead of looping over every partition in `idealState`, can we instead loop over the partitions we have locally and validate it against the `mapFields`?

Since the partition Ids we have locally are ints, we have to convert them to the format that `mapFields` has them (Test_Store_Migration_Demo_v1_0).
I think this would be the format: `storeName + localPartitionId`

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java (hunk 10 above)
Comment (kristyelee) [reply clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java]: I have written the comparison and retrieved the current host from `manager.getInstanceName().`

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java (hunk 18 above)
Comment (kristyelee) [reply clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java]: (Just to confirm, this is completed).

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java [hunk 19]
```diff
@@ -371,6 +375,31 @@ public synchronized AbstractStorageEngine openStore(
     return engine;
   }
 
+  public synchronized void checkWhetherStoragePartitionsShouldBeKeptOrNot(SafeHelixManager manager) {
+    if (manager == null) {
+      return;
+    }
+    for (AbstractStorageEngine storageEngine: getStorageEngineRepository().getAllLocalStorageEngines()) {
+      String storeName = storageEngine.getStoreVersionName();
+      Set<Integer> storageEnginePartitionIds = new HashSet<>(storageEngine.getPartitionIds());
```
Comment (kvargha) [inline clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java:384]: Since you're just looping over this, not need to convert it to a set. You can keep it as a list.

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java [hunk 20]
```diff
@@ -371,6 +375,31 @@ public synchronized AbstractStorageEngine openStore(
...
+      PropertyKey.Builder propertyKeyBuilder =
+          new PropertyKey.Builder(configLoader.getVeniceClusterConfig().getClusterName());
+      SafeHelixDataAccessor helixDataAccessor = manager.getHelixDataAccessor();
+      IdealState idealState = helixDataAccessor.getProperty(propertyKeyBuilder.idealStates(storeName));
+
+      if (idealState != null) {
+        Map<String, Map<String, String>> mapFields = idealState.getRecord().getMapFields();
+        for (Integer partitionId: storageEnginePartitionIds) {
+          String partitionDbName = storeName + "_" + partitionId;
+          if (!mapFields.get(partitionDbName).containsKey(instanceHostName)) {
```
Comment (kvargha) [inline clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java:395]: This check assumes that `partitionDbName` is in `mapFields`. To be on the safe side can you add a safeguard here that if it isn't in the `mapFields` delete it too.

Comment (kristyelee) [reply clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java]: I have added this.

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java [hunk 21]
```diff
@@ -371,6 +375,33 @@ public synchronized AbstractStorageEngine openStore(
...
+      IdealState idealState = helixDataAccessor.getProperty(propertyKeyBuilder.idealStates(storeName));
+
+      if (idealState != null) {
+        Map<String, Map<String, String>> mapFields = idealState.getRecord().getMapFields();
+        for (Integer partitionId: storageEnginePartitionIds) {
+          String partitionDbName = storeName + "_" + partitionId;
+          if (!mapFields.containsKey(partitionDbName)) {
+            storageEngine.dropPartition(partitionId);
+          } else if (!mapFields.get(partitionDbName).containsKey(instanceHostName)) {
+            storageEngine.dropPartition(partitionId);
```
Comment (kvargha) [inline clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java:398]: Instead of separating this into two if statements, can you combine the into with with an or?

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java (hunk 19 above)
Comment (kristyelee) [reply clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java:384]: [I have mutated the set, so I have created a copy to iterate over.]

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java (hunk 10 above)
Comment (kristyelee) [reply clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java]: The code logic here to consult the ideal state's information of partitions and the hosts they are assigned to [in the list discussed] has been added, and comparison to current host to determine how to keep the partition has been integrated.

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java [hunk 22]
```diff
@@ -371,6 +375,35 @@ public synchronized AbstractStorageEngine openStore(
...
+
+      if (idealState != null) {
+        Map<String, Map<String, String>> mapFields = idealState.getRecord().getMapFields();
+        for (Integer partitionId: storageEnginePartitionIds) {
+          if (storageEngine.isMetadataPartition(partitionId)) {
+            continue;
+          }
+          String partitionDbName = storeName + "_" + partitionId;
+          if (!mapFields.containsKey(partitionDbName) || (!mapFields.get(partitionDbName).containsKey(instanceHostName)
+              && !mapFields.get(partitionDbName).isEmpty())) {
```
Comment (kvargha) [inline clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java:399]: Although `!mapFields.get(partitionDbName).isEmpty()` may make the tests pass, this isn't exactly desirable behavior.

I think your existing logic is correct, but there is something wrong with the tests failing. The instance should be assigned to the partition, but it's not. I will try to back to this later this week.

Comment (kristyelee) [reply clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java:399]: For one case, ensuring the list of hosts is not empty and the current host is in the list of hosts for the partition is one case in which we delete the partition.

Comment (kvargha) [reply clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java:399]: It's possible for the `mapFields` to be empty for a `partitionDbName`, if any hosts haven't been assigned to it yet. However, in the tests that are failing, I can see that the host is being assigned in the ExternalView but not in the IdealState. So there's a problem with Helix not being updated in-time when we're trying to perform the cleanup.

Comment (kristyelee) [reply clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java:399]: Right, I understand this possibility.  
I initially thought of one possibility that coincided with the check of current host being assigned that may have made sense.

Comment (kristyelee) [reply clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java]: Commit [5e43f6f](https://github.com/linkedin/venice/commit/5e43f6f3671598deefbc6c4c3f8dea10ab0e9190) covers the change that causes the tests to pass (a check that initially could coincide). 
I have reverted the change.

**Comment by kristyelee** [comment]
The check over which storage partitions to persist is moved to the shutdown phase of VeniceServer which was discussed. 

Shutdown phase contains call to `storageService.checkWhetherStoragePartitionsShouldBeKeptOrNot`. Services are also stopped when VeniceServer shuts down.

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java [hunk 23]
```diff
@@ -371,6 +375,35 @@ public synchronized AbstractStorageEngine openStore(
...
+          new PropertyKey.Builder(configLoader.getVeniceClusterConfig().getClusterName());
+      SafeHelixDataAccessor helixDataAccessor = manager.getHelixDataAccessor();
+      IdealState idealState = helixDataAccessor.getProperty(propertyKeyBuilder.idealStates(storeName));
+
+      if (idealState != null) {
+        Map<String, Map<String, String>> mapFields = idealState.getRecord().getMapFields();
+        for (Integer partitionId: storageEnginePartitionIds) {
+          if (storageEngine.isMetadataPartition(partitionId)) {
+            continue;
+          }
```
Comment (kvargha) [inline clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java:396]: Looking through the code, `METADATA_PARTITION_ID` doesn't get added to `partitionList`, so it's safe to remove this.

File: services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java [hunk 24]
```diff
@@ -625,6 +625,8 @@ public void shutdown() throws VeniceException {
         }
       }
 
+      storageService.checkWhetherStoragePartitionsShouldBeKeptOrNot(helixParticipationService.getHelixManager());
+
```
Comment (kvargha) [inline services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java:629]: During the meeting, Zac mentioned that we should move this back to startup.

Please change it back to how it was previously. My bad.
`managerFuture.thenApply(manager -> {
      storageEngine.checkWhetherStoragePartitionsShouldBeKeptOrNot(manager);
      return true;
    });`

File: internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java [hunk 25]
```diff
@@ -182,6 +183,33 @@ public void testCheckBeforeJointClusterBeforeHelixInitializingCluster() throws E
...
+      // Create a storage engine.
+      String storeName = Version.composeKafkaTopic(cluster.createStore(1), 1);
+      storageService.openStoreForNewPartition(
+          server.getVeniceServer().getConfigLoader().getStoreConfig(storeName),
+          1,
+          () -> null);
+      Assert.assertEquals(
+          repository.getAllLocalStorageEngines().size(),
+          1,
+          "We have created one storage engine for store: " + storeName);
```
Comment (kvargha) [inline internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java:204]: You shouldn't have to do this. `cluster.createStore` should be doing this under the hood eventually.

File: services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java (hunk 24 above)
Comment (kristyelee) [reply services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java]: This has been updated accordingly.

File: internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java [hunk 26]
```diff
@@ -182,6 +183,37 @@ public void testCheckBeforeJointClusterBeforeHelixInitializingCluster() throws E
...
+      Assert.assertTrue(server.getVeniceServer().getHelixParticipationService().isRunning());
+      Assert.assertEquals(storageService.getStorageEngine(storeName).getPartitionIds().size(), 3);
+
+      server.getVeniceServer().shutdown();
+      cluster.getControllerClient().deleteStore(storeName);
+
+      cluster.stopVeniceServer(server.getPort());
+      cluster.restartVeniceServer(server.getPort());
+      repository = server.getVeniceServer().getStorageService().getStorageEngineRepository();
+      Assert.assertEquals(repository.getAllLocalStorageEngines().size(), 1);
```
Comment (kvargha) [inline internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java:212]: If we've dropped all partitions, I think we should delete the entire store.

File: internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java [hunk 27]
```diff
@@ -182,6 +183,37 @@ public void testCheckBeforeJointClusterBeforeHelixInitializingCluster() throws E
...
+      // Create a storage engine.
+      String storeName = Version.composeKafkaTopic(cluster.createStore(1), 1);
+      Assert.assertEquals(repository.getAllLocalStorageEngines().size(), 1);
+      Assert.assertTrue(server.getVeniceServer().getHelixParticipationService().isRunning());
+      Assert.assertEquals(storageService.getStorageEngine(storeName).getPartitionIds().size(), 3);
+
+      server.getVeniceServer().shutdown();
+      cluster.getControllerClient().deleteStore(storeName);
+
+      cluster.stopVeniceServer(server.getPort());
```
Comment (kvargha) [inline internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java:209]: Is this needed since you're already doing the shutdown on line 206?

Comment (kristyelee) [reply internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java:209]: Yes, the storage service cannot be obtained if I don't use `cluster.stopVeniceServer` and `cluster.restartVeniceServer.`

Comment (kvargha) [reply internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java:209]: I'm not sure I understand. 

Shutdown is performed on line 206, and on line 209 stop is called on the server.

File: internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java [hunk 28]
```diff
@@ -182,6 +183,38 @@ public void testCheckBeforeJointClusterBeforeHelixInitializingCluster() throws E
...
+
+      server.getVeniceServer().shutdown();
+
+      cluster.stopVeniceServer(server.getPort());
+      cluster.restartVeniceServer(server.getPort());
+      repository = server.getVeniceServer().getStorageService().getStorageEngineRepository();
+      Assert.assertEquals(repository.getAllLocalStorageEngines().size(), 1);
+      Assert.assertEquals(storageService.getStorageEngine(storeName).getPartitionIds().size(), 0);
+
+      cluster.getControllerClient().deleteStore(storeName);
```
[the remark this answers is not in the document]
Comment (kristyelee) [reply internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java:214]: Removing `cluster.stopVeniceServer(server.getPort())` results in an error of not being able to restart the server; removing both `cluster.stopVeniceServer(server.getPort())` and `cluster.restartVeniceServer(server.getPort())` results in not being able to fetch the storage service.

Using `cluster.stopVeniceServer` and `cluster.restartVeniceServer` without the shutdown command works.

Should I just remove `server.getVeniceServer().shutdown()` instead? I am trying this now and running the test.

File: internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java (hunk 26 above)
Comment (kvargha) [reply internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java:210]: Re-opening this one.

In our case, we're deleting the whole store which causes us to delete all of the partitions. So the `storageEngine` exists with 0 partitions. If this happens, we should drop the `storageEngine` too.

So `repository.getAllLocalStorageEngines().size()` should return 0.

File: internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java (hunk 28 above)
[the remark this answers is not in the document]
Comment (kvargha) [reply internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java]: Yes, I think removing `server.getVeniceServer().shutdown()` is the way to go.

File: internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java (hunk 26 above)
Comment (kvargha) [reply internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java:210]: Here's an [example](https://github.com/linkedin/venice/blob/78de20c7014f8dc1b86e3e1bb0d165fcb0e06911/clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java#L391-L409). If `remainingPartitions` is empty, it calls `removeStorageEngine`.

To prevent duplicate logic you could just call `dropStorePartition` and set `removeEmptyStorageEngine` to `true`.

Comment (kristyelee) [reply internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java:210]: The storage engine has been dropped upon removal of partitions.

File: internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java [hunk 29]
```diff
@@ -209,6 +209,9 @@ public void testStartServerAndShutdownWithPartitionAssignmentVerification() {
       repository = server.getVeniceServer().getStorageService().getStorageEngineRepository();
       Assert.assertEquals(repository.getAllLocalStorageEngines().size(), 1);
       Assert.assertEquals(storageService.getStorageEngine(storeName).getPartitionIds().size(), 0);
+      server.getVeniceServer().getStorageService().removeStorageEngine(storeName);
```
Comment (kvargha) [inline internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java:212]: This logic should be done in `checkWhetherStoragePartitionsShouldBeKeptOrNot`. 

If we've deleted all partitions for a `storageEngine`, we should call `removeStorageEngine`.

Comment (kvargha) [reply internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java:212]: Since `removeStorageEngine`, is now called in `checkWhetherStoragePartitionsShouldBeKeptOrNot`, you can remove line 212. Once that's in I'll kick it off to Zac.

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java [hunk 30]
```diff
@@ -371,6 +375,35 @@ public synchronized AbstractStorageEngine openStore(
...
+          if (!mapFields.containsKey(partitionDbName)
+              || !mapFields.get(partitionDbName).containsKey(instanceHostName)) {
+            storageEngine.dropPartition(partitionId);
+          }
+        }
+        if (storageEngine.getPartitionIds().isEmpty()) {
+          removeStorageEngine(storeName);
+        }
+      }
+    }
```
Comment (kvargha) [inline clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java:404]: `idealState` can be null if the store doesn't exist anymore. I'll leave it up to @ZacAttack whether or not we should remove the `storageEngine` in the else conditional.

Comment (ZacAttack) [reply clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java:404]: We should do that a it indicates a store deletion.  In which case we should clean up the disk of all partitions associated to that ideal state.

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java [hunk 31]
```diff
@@ -371,6 +375,35 @@ public synchronized AbstractStorageEngine openStore(
     return engine;
   }
 
+  public synchronized void checkWhetherStoragePartitionsShouldBeKeptOrNot(SafeHelixManager manager) {
+    if (manager == null) {
+      return;
+    }
+    for (AbstractStorageEngine storageEngine: getStorageEngineRepository().getAllLocalStorageEngines()) {
+      String storeName = storageEngine.getStoreVersionName();
+      Set<Integer> storageEnginePartitionIds = new HashSet<>(storageEngine.getPartitionIds());
```
Comment (ZacAttack) [inline clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java:384]: There is one edge case that we need to be aware of here.  Venice internally assigns a metadata partition to the storage engine.  This metadata partition exists on every Venice replica.  This metadata partition will not be part of the ideal state.  If you look at AbstractStorageEngine.METADATA_PARTITION_ID you can use this to screen dropping that particular partition (as it won't be in the ideal state).

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java [hunk 32]
```diff
@@ -371,6 +375,38 @@ public synchronized AbstractStorageEngine openStore(
...
+      PropertyKey.Builder propertyKeyBuilder =
+          new PropertyKey.Builder(configLoader.getVeniceClusterConfig().getClusterName());
+      SafeHelixDataAccessor helixDataAccessor = manager.getHelixDataAccessor();
+      IdealState idealState = helixDataAccessor.getProperty(propertyKeyBuilder.idealStates(storeName));
+
+      if (idealState != null) {
+        Map<String, Map<String, String>> mapFields = idealState.getRecord().getMapFields();
+        for (Integer partitionId: storageEnginePartitionIds) {
+          if (storageEngine.isMetadataPartition(partitionId)) {
+            storageEngine.dropPartition(partitionId);
```
Comment (kvargha) [inline clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java:395]: We should skip over deleting the metaDataPartition.

File: internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java [hunk 33]
```diff
@@ -205,10 +205,6 @@ public void testStartServerAndShutdownWithPartitionAssignmentVerification() {
 
       cluster.stopVeniceServer(server.getPort());
 
-      // Create new servers so partition assignment is removed for the offline participant
-      cluster.addVeniceServer(featureProperties, new Properties());
-      cluster.addVeniceServer(featureProperties, new Properties());
-
```
Comment (kvargha) [inline internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java]: These lines are needed, otherwise the partitions will still be assigned to the original server.

File: internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java [hunk 34]
```diff
@@ -182,6 +179,42 @@ public void testCheckBeforeJointClusterBeforeHelixInitializingCluster() throws E
...
+      cluster.addVeniceServer(featureProperties, new Properties());
+      cluster.addVeniceServer(featureProperties, new Properties());
+
+      cluster.restartVeniceServer(server.getPort());
+      repository = server.getVeniceServer().getStorageService().getStorageEngineRepository();
+      StorageEngineRepository storageEngineRepository = repository;
+      TestUtils.waitForNonDeterministicAssertion(
+          3,
+          TimeUnit.SECONDS,
+          () -> Assert.assertEquals(storageEngineRepository.getAllLocalStorageEngines().size(), 0));
```
Comment (kvargha) [inline internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java:214]: I think this whole section needs to be wrapped in `TestUtils.waitForNonDeterministicAssertion`. I'll let @ZacAttack confirm.

File: clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java [hunk 35]
```diff
@@ -371,6 +375,40 @@ public synchronized AbstractStorageEngine openStore(
...
+          }
+        }
+        if (storageEngine.getPartitionIds().isEmpty()) {
+          removeStorageEngine(storeName);
+        }
+      } else {
+        removeStorageEngine(storeName);
+      }
+    }
```
Comment (kvargha) [inline clients/da-vinci-client/src/main/java/com/linkedin/davinci/storage/StorageService.java:409]: Can we please add some logging here to indicate that we're deleting partitions, storage engines? It would be helpful for debugging in the case we observe unnecessary boostrapping.

File: internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java (hunk 34 above)
Comment (ZacAttack) [reply internal/venice-test-common/src/integrationTest/java/com/linkedin/venice/server/VeniceServerTest.java]: Nah this is actually ok.  We're basically just doing the restart and waiting for what we need to happen.  In which case we need to only wait on the assert.

**Review by ZacAttack — APPROVED** [review]
Looks good!  Great work, thank you for all the effort!

**Review by kvargha — APPROVED** [review]

**Comment by kvargha** [comment]
Congratulations on merging your first PR into Venice @kristyelee. Thank you for your persistence.

File: services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java [hunk 36]
```diff
@@ -355,6 +355,11 @@ private List<AbstractVeniceService> createServices() {
       return helixData;
     });
 
+    managerFuture.thenApply(manager -> {
+      storageService.checkWhetherStoragePartitionsShouldBeKeptOrNot(manager);
+      return true;
+    });
+
```
Comment (huangminchn) [inline services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java:362]: What if Helix couldn't compute the new Ideal state quick enough after the host is restarted and connected? Server might delete everything and rebootstrap from scratch?

Comment (ZacAttack) [reply services/venice-server/src/main/java/com/linkedin/venice/server/VeniceServer.java:362]: So a restarted host shouldn't alter the idealstate.  idealstate will only be altered after a rebalance has occurred, which will only happen in cases where the node was down for an extended period.
